### ISSUE TITLE
Load <script>s in the head?

### ISSUE THREAD

**Issue by davidrunger** [appacademy/asteroids.js#1]
In the instructions and this solution we tell students to load their `<script>s` in the head. Why?

My understanding is that it is generally best practice (i.e. fastest user experience) to load JS files just before the `</body>` tag unless one has a reason to do otherwise. Is there a reason that in this case we
would want/need to load our JS files in the `<head>` (thus delaying the loading of the rest of our page)? I can't think of one. I already took the liberty of removing that directive from the instructions (https://github.com/appacademy/js-curriculum/commit/dad4fb0c76d75d45d830b0d18f2f5c26c89555f2), but before I change it in the solution I wanted to make sure that I'm not missing something.

**Comment by rglassett** [comment]
I think you're right that it's usually best to load scripts before the closing `</body>` tag. I don't think it much matters in this case, though, as we're not really rendering any content. It's difficult to do in Rails as well, since loading javascripts after the `<% yield %>` block could break scripts in the template.

**Comment by davidrunger** [comment]
Thanks for chiming in, Ryan! :smiley: 

Yes, I agree it is basically irrelevant here, and I am also aware of how hard it is to do this in Rails (I tried for my final project... I wanted that Google PageSpeed score!). But I figure that we might as well demonstrate best practices where we can.

I'll go ahead and make this change, then.

**Comment by nerfologist** [comment]
If I can bring my 2 cents of experience trying to achieve this: based on a tip by @w1zeman1p during my final project, I modified my app's `layout.html.erb` this way:

```
<body>
<div id='main'>
  <%= yield %>
</div>
  <%= javascript_include_tag 'application' %>
  <%= yield :scripts %>
</body>
```

Then I modified my static (backbone init) page to only include this block:

```
<% content_for :scripts  do %>
<script>
$(document).ready(function(){
  LiteTracker.initialize();
});
</script>
<% end %>
```

This solution makes sure that all scripts are loaded just before `</body>`, and that backbone initialization still works.

I thought it was pretty cool at the time! :smile:

**Comment by rglassett** [comment]
Excellent tip, we should definitely teach this with the rest of our
performance material. Thanks!
